### ISSUE TITLE
Note about haml-lint vs haml_lint is incorrect now

### ISSUE THREAD

**Issue by LeEnno** [SublimeLinter/SublimeLinter-haml-lint#6]
Basically the mass replacement in https://github.com/jeroenj/SublimeLinter-contrib-haml-lint/commit/ccd970eb4512f2510c57f951e44a02ddd4364905 broke https://github.com/jeroenj/SublimeLinter-contrib-haml-lint/pull/5.

Also the executable is still called `haml-lint` with a dash,`haml_lint` with an underscore is only the gem name. So imho it's not appropriate to rename every single occurrence of `haml-lint` to `haml_lint`.

**Comment by jeroenj** [comment]
Good catch. Fixed the warning and changed it to reference `haml-lint` instead of `haml_lint` again.

This stuff is so confusing. 😅
